services:
  todo-mongo:
    image: mongo:8.0.9
    ports:
      - 27017:27017
    container_name: todo-mongo
    restart: always
    volumes:
      - mongo-volume:/data/db
    networks:
      - todo-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: todo
      MONGO_INITDB_ROOT_PASSWORD: todo-pwd
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 2048M
        reservations:
          cpus: '2.0'
          memory: 1024M

networks:
  todo-network:
    external: true
      

volumes:
  mongo-volume: