services:
  todo-core:
    container_name: todo-core
    build:
      dockerfile: src/main/docker/Dockerfile.jvm
      context: .
    ports:
      - 8080:8080
    environment:
      - quarkus.mongodb.connection-string=mongodb://todo:todo-pwd@todo-mongo
      - quarkus.mongodb.database=tododb
      - quarkus.http.cors=true
      - quarkus.http.cors.headers=core-key, Authorization, Content-Type
      - quarkus.http.cors.access-control-max-age=12H
      - quarkus.http.cors.origins=/.*/
    networks:
      - todo-network
      

  todo-mongo:
    image: mongo:8.0.9
    ports:
      - 27017:27017
    container_name: todo-mongo
    restart: always
    volumes:
      - mongo-volume:/data/db
    networks:
      - todo-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: todo
      MONGO_INITDB_ROOT_PASSWORD: todo-pwd
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 2048M
        reservations:
          cpus: '2.0'
          memory: 1024M

networks:
  todo-network:
    external: true
      

volumes:
  mongo-volume: